### ISSUE TITLE
Registration Report - Memberships Sold

### ISSUE THREAD

**Issue by dleverentz** [CON-In-A-Box/CIAB-Portal#398]
As a Registration Head/Sub-Head, I can view a report showing a list of all memberships sold for the current event, so I can perform analysis and troubleshoot. 

**Acceptance Criteria**

- [ ] Provides the following information in this order for each membership sold: 

- Account ID
- Badge Number
- Preferred First Name
- Preferred Last Name
- Legal First Name
- Legal Last Name
- Badge Type
- Badge Cost
- Date Sold

- [ ] Provides this information in the browser window
- [ ] Provides the ability to export the report as a CSV file

**Comment by AricStewart** [comment]
Development finished, code in master.

**Comment by dleverentz** [comment]
Reviewed in DEV - view report button did not work, download CSV button worked. 
Report format looks good. 
No data was pulled, so I can't validate that we are pulling correct data. @AricStewart should there have been data?

**Comment by AricStewart** [comment]
Try ciab.anergyst.org   credentials mailed to you.
